null = ""
true = "true"
false = "false"

test_data = {"notifications": [{"threatInfo": {"incidentId": "Z7NG6", "score": 7,
                                               "summary": "A known virus (Sality: Keylogger, Password or Data stealer, Backdoor) was detected running.",
                                               "indicators": [{"indicatorName": "PACKED_CALL",
                                                               "applicationName": "ShippingInvoice.pdf.exe",
                                                               "sha256Hash": "cfe0ae57f314a9f747a7cec605907cdaf1984b3cdea74ee8d5893d00ae0886cc"},
                                                              {"indicatorName": "TARGET_MALWARE_APP",
                                                               "applicationName": "explorer.exe",
                                                               "sha256Hash": "1e675cb7df214172f7eb0497f7275556038a0d09c6e5a3e6862c5e26885ef455"},
                                                              {"indicatorName": "HAS_PACKED_CODE",
                                                               "applicationName": "ShippingInvoice.pdf.exe",
                                                               "sha256Hash": "cfe0ae57f314a9f747a7cec605907cdaf1984b3cdea74ee8d5893d00ae0886cc"},
                                                              {"indicatorName": "KNOWN_DOWNLOADER",
                                                               "applicationName": "ShippingInvoice.pdf.exe",
                                                               "sha256Hash": "cfe0ae57f314a9f747a7cec605907cdaf1984b3cdea74ee8d5893d00ae0886cc"},
                                                              {"indicatorName": "ENUMERATE_PROCESSES",
                                                               "applicationName": "ShippingInvoice.pdf.exe",
                                                               "sha256Hash": "cfe0ae57f314a9f747a7cec605907cdaf1984b3cdea74ee8d5893d00ae0886cc"},
                                                              {"indicatorName": "SET_SYSTEM_SECURITY",
                                                               "applicationName": "ShippingInvoice.pdf.exe",
                                                               "sha256Hash": "cfe0ae57f314a9f747a7cec605907cdaf1984b3cdea74ee8d5893d00ae0886cc"},
                                                              {"indicatorName": "MODIFY_MEMORY_PROTECTION",
                                                               "applicationName": "ShippingInvoice.pdf.exe",
                                                               "sha256Hash": "cfe0ae57f314a9f747a7cec605907cdaf1984b3cdea74ee8d5893d00ae0886cc"},
                                                              {"indicatorName": "KNOWN_PASSWORD_STEALER",
                                                               "applicationName": "ShippingInvoice.pdf.exe",
                                                               "sha256Hash": "cfe0ae57f314a9f747a7cec605907cdaf1984b3cdea74ee8d5893d00ae0886cc"},
                                                              {"indicatorName": "RUN_MALWARE_APP",
                                                               "applicationName": "explorer.exe",
                                                               "sha256Hash": "1e675cb7df214172f7eb0497f7275556038a0d09c6e5a3e6862c5e26885ef455"},
                                                              {"indicatorName": "MODIFY_PROCESS",
                                                               "applicationName": "ShippingInvoice.pdf.exe",
                                                               "sha256Hash": "cfe0ae57f314a9f747a7cec605907cdaf1984b3cdea74ee8d5893d00ae0886cc"},
                                                              {"indicatorName": "MALWARE_APP",
                                                               "applicationName": "ShippingInvoice.pdf.exe",
                                                               "sha256Hash": "cfe0ae57f314a9f747a7cec605907cdaf1984b3cdea74ee8d5893d00ae0886cc"}],
                                               "time": 1460703240678},
                                "url": "https://testserver.company.net/ui#investigate/events/device/2004118/incident/Z7NG6",
                                "eventTime": 1460703240678, "eventId": "f279d0e6035211e6be8701df2c083974",
                                "eventDescription": "[syslog alert] [Cb Defense has detected a threat against your company.] [https://testserver.company.net/ui#device/2004118/incident/Z7NG6] [A known virus (Sality: Keylogger, Password or Data stealer, Backdoor) was detected running.] [Incident id: Z7NG6] [Threat score: 7] [Group: default] [Email: FirstName.LastName@company.net.demo] [Name: Demo_CaretoPC] [Type and OS: WINDOWS XP x86 SP: 0]\n",
                                "deviceInfo": {"email": "COMPANY\\FirstName.LastName", "groupName": "default",
                                               "internalIpAddress": null, "externalIpAddress": null,
                                               "deviceType": "WINDOWS", "deviceVersion": "XP x86 SP: 0",
                                               "targetPriorityType": "MEDIUM", "deviceId": 2004118,
                                               "deviceName": "COMPANY\\Demo_CaretoPC", "deviceHostName": null,
                                               "targetPriorityCode": 0}, "ruleName": "syslog alert",
                                "type": "THREAT"}, {"threatInfo": {"incidentId": "YL5RZ", "score": 7,
                                                                   "summary": "A known virus (Sality: Keylogger, Password or Data stealer, Backdoor) was detected running.",
                                                                   "indicators": [
                                                                       {"indicatorName": "PACKED_CALL",
                                                                        "applicationName": "ShippingInvoice.pdf.exe",
                                                                        "sha256Hash": "cfe0ae57f314a9f747a7cec605907cdaf1984b3cdea74ee8d5893d00ae0886cc"},
                                                                       {"indicatorName": "MODIFY_PROCESS",
                                                                        "applicationName": "ShippingInvoice.pdf.exe",
                                                                        "sha256Hash": "cfe0ae57f314a9f747a7cec605907cdaf1984b3cdea74ee8d5893d00ae0886cc"},
                                                                       {"indicatorName": "ENUMERATE_PROCESSES",
                                                                        "applicationName": "ShippingInvoice.pdf.exe",
                                                                        "sha256Hash": "cfe0ae57f314a9f747a7cec605907cdaf1984b3cdea74ee8d5893d00ae0886cc"},
                                                                       {"indicatorName": "MALWARE_APP",
                                                                        "applicationName": "ShippingInvoice.pdf.exe",
                                                                        "sha256Hash": "cfe0ae57f314a9f747a7cec605907cdaf1984b3cdea74ee8d5893d00ae0886cc"},
                                                                       {"indicatorName": "SET_SYSTEM_SECURITY",
                                                                        "applicationName": "ShippingInvoice.pdf.exe",
                                                                        "sha256Hash": "cfe0ae57f314a9f747a7cec605907cdaf1984b3cdea74ee8d5893d00ae0886cc"},
                                                                       {"indicatorName": "KNOWN_DOWNLOADER",
                                                                        "applicationName": "ShippingInvoice.pdf.exe",
                                                                        "sha256Hash": "cfe0ae57f314a9f747a7cec605907cdaf1984b3cdea74ee8d5893d00ae0886cc"},
                                                                       {"indicatorName": "HAS_PACKED_CODE",
                                                                        "applicationName": "ShippingInvoice.pdf.exe",
                                                                        "sha256Hash": "cfe0ae57f314a9f747a7cec605907cdaf1984b3cdea74ee8d5893d00ae0886cc"},
                                                                       {
                                                                           "indicatorName": "KNOWN_PASSWORD_STEALER",
                                                                           "applicationName": "ShippingInvoice.pdf.exe",
                                                                           "sha256Hash": "cfe0ae57f314a9f747a7cec605907cdaf1984b3cdea74ee8d5893d00ae0886cc"},
                                                                       {
                                                                           "indicatorName": "MODIFY_MEMORY_PROTECTION",
                                                                           "applicationName": "ShippingInvoice.pdf.exe",
                                                                           "sha256Hash": "cfe0ae57f314a9f747a7cec605907cdaf1984b3cdea74ee8d5893d00ae0886cc"}],
                                                                   "time": 1460703240678},
                                                    "url": "https://testserver.company.net/ui#investigate/events/device/2004118/incident/YL5RZ",
                                                    "eventTime": 1460703240678,
                                                    "eventId": "f44087c9035211e6aab2b97cae4f83f3",
                                                    "eventDescription": "[syslog alert] [Cb Defense has detected a threat against your company.] [https://testserver.company.net/ui#device/2004118/incident/YL5RZ] [A known virus (Sality: Keylogger, Password or Data stealer, Backdoor) was detected running.] [Incident id: YL5RZ] [Threat score: 7] [Group: default] [Email: FirstName.LastName@company.net.demo] [Name: Demo_CaretoPC] [Type and OS: WINDOWS XP x86 SP: 0]\n",
                                                    "deviceInfo": {
                                                        "email": "COMPANY\\FirstName.LastName@company.net.demo",
                                                        "groupName": "default", "internalIpAddress": null,
                                                        "externalIpAddress": null, "deviceType": "WINDOWS",
                                                        "deviceVersion": "XP x86 SP: 0",
                                                        "targetPriorityType": "MEDIUM", "deviceId": 2004118,
                                                        "deviceName": "COMPANY\\Demo_CaretoPC",
                                                        "deviceHostName": null, "targetPriorityCode": 0},
                                                    "ruleName": "syslog alert", "type": "THREAT"}, {
                                   "threatInfo": {"incidentId": "IDWID", "score": 7,
                                                  "summary": "A known virus (iWorm) is actively attempting a network connection.",
                                                  "indicators": [{"indicatorName": "ATTEMPTED_CLIENT",
                                                                  "applicationName": "Mac.BackDoor.iWorm_sample_2",
                                                                  "sha256Hash": "0b374d3dfd2fcae65d191dd1810cd8cc0b497c48b509f260654b0f3fe4cc9f8f"},
                                                                 {"indicatorName": "ACTIVE_CLIENT",
                                                                  "applicationName": "Mac.BackDoor.iWorm_sample_2",
                                                                  "sha256Hash": "0b374d3dfd2fcae65d191dd1810cd8cc0b497c48b509f260654b0f3fe4cc9f8f"},
                                                                 {"indicatorName": "KNOWN_MALWARE_ON_NETWORK",
                                                                  "applicationName": "Mac.BackDoor.iWorm_sample_2",
                                                                  "sha256Hash": "0b374d3dfd2fcae65d191dd1810cd8cc0b497c48b509f260654b0f3fe4cc9f8f"},
                                                                 {"indicatorName": "RUN_SYSTEM_APP",
                                                                  "applicationName": "Mac.BackDoor.iWorm_sample_2",
                                                                  "sha256Hash": "0b374d3dfd2fcae65d191dd1810cd8cc0b497c48b509f260654b0f3fe4cc9f8f"},
                                                                 {"indicatorName": "MALWARE_APP",
                                                                  "applicationName": "Mac.BackDoor.iWorm_sample_2",
                                                                  "sha256Hash": "0b374d3dfd2fcae65d191dd1810cd8cc0b497c48b509f260654b0f3fe4cc9f8f"},
                                                                 {"indicatorName": "BEACON",
                                                                  "applicationName": "Mac.BackDoor.iWorm_sample_2",
                                                                  "sha256Hash": "0b374d3dfd2fcae65d191dd1810cd8cc0b497c48b509f260654b0f3fe4cc9f8f"},
                                                                 {"indicatorName": "INTERNATIONAL_SITE",
                                                                  "applicationName": "Mac.BackDoor.iWorm_sample_2",
                                                                  "sha256Hash": "0b374d3dfd2fcae65d191dd1810cd8cc0b497c48b509f260654b0f3fe4cc9f8f"},
                                                                 {"indicatorName": "RUN_ANOTHER_APP",
                                                                  "applicationName": "Mac.BackDoor.iWorm_sample_2",
                                                                  "sha256Hash": "0b374d3dfd2fcae65d191dd1810cd8cc0b497c48b509f260654b0f3fe4cc9f8f"},
                                                                 {"indicatorName": "NETWORK_ACCESS",
                                                                  "applicationName": "Mac.BackDoor.iWorm_sample_2",
                                                                  "sha256Hash": "0b374d3dfd2fcae65d191dd1810cd8cc0b497c48b509f260654b0f3fe4cc9f8f"}],
                                                  "time": 1460751097691},
                                   "url": "https://testserver.company.net/ui#investigate/events/device/2004121/incident/IDWID",
                                   "eventTime": 1460751097691, "eventId": "f66bcb98035211e6be8701df2c083974",
                                   "eventDescription": "[syslog alert] [Cb Defense has detected a threat against your company.] [https://testserver.company.net/ui#device/2004121/incident/IDWID] [A known virus (iWorm) is actively attempting a network connection.] [Incident id: IDWID] [Threat score: 7] [Group: default] [Email: iworm_test@company.net.demo] [Name: iworm_test] [Type and OS: MAC MAC OS X 10.9.0]\n",
                                   "deviceInfo": {"email": "COMPANY\\iworm_test", "groupName": "default",
                                                  "internalIpAddress": null, "externalIpAddress": null,
                                                  "deviceType": "MAC", "deviceVersion": "MAC OS X 10.9.0",
                                                  "targetPriorityType": "MEDIUM", "deviceId": 2004121,
                                                  "deviceName": "COMPANY\\iworm_test", "deviceHostName": null,
                                                  "targetPriorityCode": 0}, "ruleName": "syslog alert",
                                   "type": "THREAT"}, {"threatInfo": {"incidentId": "UHMZ3", "score": 7,
                                                                      "summary": "A known virus (iWorm) is actively attempting a network connection.",
                                                                      "indicators": [
                                                                          {"indicatorName": "MALWARE_APP",
                                                                           "applicationName": "Mac.BackDoor.iWorm_sample_2",
                                                                           "sha256Hash": "0b374d3dfd2fcae65d191dd1810cd8cc0b497c48b509f260654b0f3fe4cc9f8f"},
                                                                          {"indicatorName": "INTERNATIONAL_SITE",
                                                                           "applicationName": "Mac.BackDoor.iWorm_sample_2",
                                                                           "sha256Hash": "0b374d3dfd2fcae65d191dd1810cd8cc0b497c48b509f260654b0f3fe4cc9f8f"},
                                                                          {"indicatorName": "NETWORK_ACCESS",
                                                                           "applicationName": "Mac.BackDoor.iWorm_sample_2",
                                                                           "sha256Hash": "0b374d3dfd2fcae65d191dd1810cd8cc0b497c48b509f260654b0f3fe4cc9f8f"},
                                                                          {
                                                                              "indicatorName": "KNOWN_MALWARE_ON_NETWORK",
                                                                              "applicationName": "Mac.BackDoor.iWorm_sample_2",
                                                                              "sha256Hash": "0b374d3dfd2fcae65d191dd1810cd8cc0b497c48b509f260654b0f3fe4cc9f8f"},
                                                                          {"indicatorName": "BEACON",
                                                                           "applicationName": "Mac.BackDoor.iWorm_sample_2",
                                                                           "sha256Hash": "0b374d3dfd2fcae65d191dd1810cd8cc0b497c48b509f260654b0f3fe4cc9f8f"},
                                                                          {"indicatorName": "ATTEMPTED_CLIENT",
                                                                           "applicationName": "Mac.BackDoor.iWorm_sample_2",
                                                                           "sha256Hash": "0b374d3dfd2fcae65d191dd1810cd8cc0b497c48b509f260654b0f3fe4cc9f8f"},
                                                                          {"indicatorName": "RUN_MALWARE_APP",
                                                                           "applicationName": "bash",
                                                                           "sha256Hash": "737867f9e519c2eae2b064c33dc0608b283ebd6045fcf8b19736651ec34c0e37"},
                                                                          {"indicatorName": "RUN_SYSTEM_APP",
                                                                           "applicationName": "Mac.BackDoor.iWorm_sample_2",
                                                                           "sha256Hash": "0b374d3dfd2fcae65d191dd1810cd8cc0b497c48b509f260654b0f3fe4cc9f8f"},
                                                                          {"indicatorName": "ACTIVE_CLIENT",
                                                                           "applicationName": "Mac.BackDoor.iWorm_sample_2",
                                                                           "sha256Hash": "0b374d3dfd2fcae65d191dd1810cd8cc0b497c48b509f260654b0f3fe4cc9f8f"},
                                                                          {"indicatorName": "TARGET_MALWARE_APP",
                                                                           "applicationName": "bash",
                                                                           "sha256Hash": "737867f9e519c2eae2b064c33dc0608b283ebd6045fcf8b19736651ec34c0e37"},
                                                                          {"indicatorName": "RUN_ANOTHER_APP",
                                                                           "applicationName": "Mac.BackDoor.iWorm_sample_2",
                                                                           "sha256Hash": "0b374d3dfd2fcae65d191dd1810cd8cc0b497c48b509f260654b0f3fe4cc9f8f"}],
                                                                      "time": 1460751097691},
                                                       "url": "https://testserver.company.net/ui#investigate/events/device/2004121/incident/UHMZ3",
                                                       "eventTime": 1460751097691,
                                                       "eventId": "f7e85a1c035211e6aab2b97cae4f83f3",
                                                       "eventDescription": "[syslog alert] [Cb Defense has detected a threat against your company.] [https://testserver.company.net/ui#device/2004121/incident/UHMZ3] [A known virus (iWorm) is actively attempting a network connection.] [Incident id: UHMZ3] [Threat score: 7] [Group: default] [Email: iworm_test@company.net.demo] [Name: iworm_test] [Type and OS: MAC MAC OS X 10.9.0]\n",
                                                       "deviceInfo": {"email": "COMPANY\\iworm_test",
                                                                      "groupName": "default",
                                                                      "internalIpAddress": null,
                                                                      "externalIpAddress": null,
                                                                      "deviceType": "MAC",
                                                                      "deviceVersion": "MAC OS X 10.9.0",
                                                                      "targetPriorityType": "MEDIUM",
                                                                      "deviceId": 2004121,
                                                                      "deviceName": "COMPANY\\iworm_test",
                                                                      "deviceHostName": null,
                                                                      "targetPriorityCode": 0},
                                                       "ruleName": "syslog alert", "type": "THREAT"}, {
                                   "threatInfo": {"incidentId": "DKI00", "score": 3,
                                                  "summary": "An unknown, suspect or compromised application, has exhibited dangerous virus-like behavior.",
                                                  "indicators": [{"indicatorName": "ENUMERATE_PROCESSES",
                                                                  "applicationName": "osxinj",
                                                                  "sha256Hash": "8cae6527b19ddc3395f09b537c727bbfaa5a0fe010ae42229d3d1b4470f2434b"},
                                                                 {"indicatorName": "INJECT_CODE",
                                                                  "applicationName": "osxinj",
                                                                  "sha256Hash": "8cae6527b19ddc3395f09b537c727bbfaa5a0fe010ae42229d3d1b4470f2434b"},
                                                                 {"indicatorName": "SUSPICIOUS_BEHAVIOR",
                                                                  "applicationName": "osxinj",
                                                                  "sha256Hash": "8cae6527b19ddc3395f09b537c727bbfaa5a0fe010ae42229d3d1b4470f2434b"}],
                                                  "time": 1460752031552},
                                   "url": "https://testserver.company.net/ui#investigate/events/device/2004120/incident/DKI00",
                                   "eventTime": 1460752031552, "eventId": "fb1752ee035211e6aab2b97cae4f83f3",
                                   "eventDescription": "[syslog alert] [Cb Defense has detected a threat against your company.] [https://testserver.company.net/ui#device/2004120/incident/DKI00] [An unknown, suspect or compromised application, has exhibited dangerous virus-like behavior.] [Incident id: DKI00] [Threat score: 3] [Group: default] [Email: osxInjection@company.net.demo] [Name: Demo_Mac_Injection] [Type and OS: MAC MAC OS X 10.9.0]\n",
                                   "deviceInfo": {"email": "osxInjection@company.net.demo",
                                                  "groupName": "default", "internalIpAddress": null,
                                                  "externalIpAddress": null, "deviceType": "MAC",
                                                  "deviceVersion": "MAC OS X 10.9.0",
                                                  "targetPriorityType": "MEDIUM", "deviceId": 2004120,
                                                  "deviceName": "Demo_Mac_Injection", "deviceHostName": null,
                                                  "targetPriorityCode": 0}, "ruleName": "syslog alert",
                                   "type": "THREAT"}, {"threatInfo": {"incidentId": "140XP", "score": 7,
                                                                      "summary": "A known virus (Thoper: Keylogger, Password or Data stealer, Backdoor) was detected running.",
                                                                      "indicators": [{
                                                                          "indicatorName": "MODIFY_MEMORY_PROTECTION",
                                                                          "applicationName": "win3dx.DLL",
                                                                          "sha256Hash": "ba6db998cda7cdaa7eea235e26776d1bed99c73f4c9789ed70c98053a8d18559"},
                                                                          {
                                                                              "indicatorName": "MALWARE_APP",
                                                                              "applicationName": "win3dx.DLL",
                                                                              "sha256Hash": "ba6db998cda7cdaa7eea235e26776d1bed99c73f4c9789ed70c98053a8d18559"},
                                                                          {
                                                                              "indicatorName": "KNOWN_BACKDOOR",
                                                                              "applicationName": "win3dx.DLL",
                                                                              "sha256Hash": "ba6db998cda7cdaa7eea235e26776d1bed99c73f4c9789ed70c98053a8d18559"},
                                                                          {
                                                                              "indicatorName": "KNOWN_PASSWORD_STEALER",
                                                                              "applicationName": "win3dx.DLL",
                                                                              "sha256Hash": "ba6db998cda7cdaa7eea235e26776d1bed99c73f4c9789ed70c98053a8d18559"},
                                                                          {
                                                                              "indicatorName": "KNOWN_KEYLOGGER",
                                                                              "applicationName": "win3dx.DLL",
                                                                              "sha256Hash": "ba6db998cda7cdaa7eea235e26776d1bed99c73f4c9789ed70c98053a8d18559"},
                                                                          {
                                                                              "indicatorName": "MODIFY_SERVICE",
                                                                              "applicationName": "win3dx.DLL",
                                                                              "sha256Hash": "ba6db998cda7cdaa7eea235e26776d1bed99c73f4c9789ed70c98053a8d18559"}],
                                                                      "time": 1460752197249},
                                                       "url": "https://testserver.company.net/ui#investigate/events/device/2004116/incident/140XP",
                                                       "eventTime": 1460752197249,
                                                       "eventId": "f73005f9035211e6be8701df2c083974",
                                                       "eventDescription": "[syslog alert] [Cb Defense has detected a threat against your company.] [https://testserver.company.net/ui#device/2004116/incident/140XP] [A known virus (Thoper: Keylogger, Password or Data stealer, Backdoor) was detected running.] [Incident id: 140XP] [Threat score: 7] [Group: default] [Email: rat01@company.net.demo] [Name: Demo_RAT_01] [Type and OS: WINDOWS XP x86 SP: 0]\n",
                                                       "deviceInfo": {"email": "COMPANY\\rat01@company.net.demo",
                                                                      "groupName": "default",
                                                                      "internalIpAddress": null,
                                                                      "externalIpAddress": null,
                                                                      "deviceType": "WINDOWS",
                                                                      "deviceVersion": "XP x86 SP: 0",
                                                                      "targetPriorityType": "MEDIUM",
                                                                      "deviceId": 2004116,
                                                                      "deviceName": "COMPANY\\Demo_RAT_01",
                                                                      "deviceHostName": null,
                                                                      "targetPriorityCode": 0},
                                                       "ruleName": "syslog alert", "type": "THREAT"}, {
                                   "threatInfo": {"incidentId": "VPJZJ", "score": 7,
                                                  "summary": "A known virus (Keylogger, Password or Data stealer, Backdoor) was detected running.",
                                                  "indicators": [{"indicatorName": "MODIFY_SERVICE",
                                                                  "applicationName": "win3dx.DLL",
                                                                  "sha256Hash": "ba6db998cda7cdaa7eea235e26776d1bed99c73f4c9789ed70c98053a8d18559"},
                                                                 {"indicatorName": "KNOWN_KEYLOGGER",
                                                                  "applicationName": "win3dx.DLL",
                                                                  "sha256Hash": "ba6db998cda7cdaa7eea235e26776d1bed99c73f4c9789ed70c98053a8d18559"},
                                                                 {"indicatorName": "KNOWN_PASSWORD_STEALER",
                                                                  "applicationName": "win3dx.DLL",
                                                                  "sha256Hash": "ba6db998cda7cdaa7eea235e26776d1bed99c73f4c9789ed70c98053a8d18559"},
                                                                 {"indicatorName": "CODE_DROP",
                                                                  "applicationName": "explorer.exe",
                                                                  "sha256Hash": "1e675cb7df214172f7eb0497f7275556038a0d09c6e5a3e6862c5e26885ef455"},
                                                                 {"indicatorName": "MALWARE_APP",
                                                                  "applicationName": "win3dx.DLL",
                                                                  "sha256Hash": "ba6db998cda7cdaa7eea235e26776d1bed99c73f4c9789ed70c98053a8d18559"},
                                                                 {"indicatorName": "MALWARE_DROP",
                                                                  "applicationName": "explorer.exe",
                                                                  "sha256Hash": "1e675cb7df214172f7eb0497f7275556038a0d09c6e5a3e6862c5e26885ef455"},
                                                                 {"indicatorName": "TARGET_MALWARE_APP",
                                                                  "applicationName": "explorer.exe",
                                                                  "sha256Hash": "1e675cb7df214172f7eb0497f7275556038a0d09c6e5a3e6862c5e26885ef455"},
                                                                 {"indicatorName": "MODIFY_MEMORY_PROTECTION",
                                                                  "applicationName": "win3dx.DLL",
                                                                  "sha256Hash": "ba6db998cda7cdaa7eea235e26776d1bed99c73f4c9789ed70c98053a8d18559"},
                                                                 {"indicatorName": "KNOWN_BACKDOOR",
                                                                  "applicationName": "win3dx.DLL",
                                                                  "sha256Hash": "ba6db998cda7cdaa7eea235e26776d1bed99c73f4c9789ed70c98053a8d18559"},
                                                                 {"indicatorName": "RUN_MALWARE_APP",
                                                                  "applicationName": "svchost.exe",
                                                                  "sha256Hash": "2910ebc692d833d949bfd56059e8106d324a276d5f165f874f3fb1b6c613cdd5"}],
                                                  "time": 1460752198380},
                                   "url": "https://testserver.company.net/ui#investigate/events/device/2004116/incident/VPJZJ",
                                   "eventTime": 1460752198380, "eventId": "f72cf95a035211e6aab2b97cae4f83f3",
                                   "eventDescription": "[syslog alert] [Cb Defense has detected a threat against your company.] [https://testserver.company.net/ui#device/2004116/incident/VPJZJ] [A known virus (Keylogger, Password or Data stealer, Backdoor) was detected running.] [Incident id: VPJZJ] [Threat score: 7] [Group: default] [Email: rat01@company.net.demo] [Name: Demo_RAT_01] [Type and OS: WINDOWS XP x86 SP: 0]\n",
                                   "deviceInfo": {"email": "COMPANY\\rat01@company.net.demo",
                                                  "groupName": "default", "internalIpAddress": null,
                                                  "externalIpAddress": null, "deviceType": "WINDOWS",
                                                  "deviceVersion": "XP x86 SP: 0",
                                                  "targetPriorityType": "MEDIUM", "deviceId": 2004116,
                                                  "deviceName": "COMPANY\\Demo_RAT_01", "deviceHostName": null,
                                                  "targetPriorityCode": 0}, "ruleName": "syslog alert",
                                   "type": "THREAT"}, {"threatInfo": {"incidentId": "6OJFC", "score": 3,
                                                                      "summary": "A known virus (FakeRean) was detected running.",
                                                                      "indicators": [
                                                                          {"indicatorName": "KNOWN_ROGUE",
                                                                           "applicationName": "svc.exe",
                                                                           "sha256Hash": "a37dd4f85117539ce4401c02c2bea403d7a724bedaccb5969980c8cf39b2a01a"},
                                                                          {
                                                                              "indicatorName": "MODIFY_MEMORY_PROTECTION",
                                                                              "applicationName": "svc.exe",
                                                                              "sha256Hash": "a37dd4f85117539ce4401c02c2bea403d7a724bedaccb5969980c8cf39b2a01a"},
                                                                          {"indicatorName": "MODIFY_OWN_PROCESS",
                                                                           "applicationName": "svc.exe",
                                                                           "sha256Hash": "a37dd4f85117539ce4401c02c2bea403d7a724bedaccb5969980c8cf39b2a01a"},
                                                                          {"indicatorName": "MALWARE_APP",
                                                                           "applicationName": "svc.exe",
                                                                           "sha256Hash": "a37dd4f85117539ce4401c02c2bea403d7a724bedaccb5969980c8cf39b2a01a"},
                                                                          {"indicatorName": "PACKED_CALL",
                                                                           "applicationName": "svc.exe",
                                                                           "sha256Hash": "a37dd4f85117539ce4401c02c2bea403d7a724bedaccb5969980c8cf39b2a01a"},
                                                                          {"indicatorName": "HAS_PACKED_CODE",
                                                                           "applicationName": "svc.exe",
                                                                           "sha256Hash": "a37dd4f85117539ce4401c02c2bea403d7a724bedaccb5969980c8cf39b2a01a"}],
                                                                      "time": 1460752321085},
                                                       "url": "https://testserver.company.net/ui#investigate/events/device/2004122/incident/6OJFC",
                                                       "eventTime": 1460752321085,
                                                       "eventId": "f73313db035211e6aab2b97cae4f83f3",
                                                       "eventDescription": "[syslog alert] [Cb Defense has detected a threat against your company.] [https://testserver.company.net/ui#device/2004122/incident/6OJFC] [A known virus (FakeRean) was detected running.] [Incident id: 6OJFC] [Threat score: 3] [Group: default] [Email: fakeav_driveby@company.net.demo] [Name: fakeav_driveby] [Type and OS: WINDOWS Windows 7 x86 SP: 0]\n",
                                                       "deviceInfo": {
                                                           "email": "COMPANY\\fakeav_driveby@company.net.demo",
                                                           "groupName": "default", "internalIpAddress": null,
                                                           "externalIpAddress": null, "deviceType": "WINDOWS",
                                                           "deviceVersion": "Windows 7 x86 SP: 0",
                                                           "targetPriorityType": "MEDIUM", "deviceId": 2004122,
                                                           "deviceName": "COMPANY\\fakeav_driveby",
                                                           "deviceHostName": null, "targetPriorityCode": 0},
                                                       "ruleName": "syslog alert", "type": "THREAT"}, {
                                   "threatInfo": {"incidentId": "DRE26", "score": 4,
                                                  "summary": "An application has created an executable which is a known virus or on the Company Black List.",
                                                  "indicators": [{"indicatorName": "HAS_SCRIPT_DLL",
                                                                  "applicationName": "iexplore.exe",
                                                                  "sha256Hash": "422d380855c449e81a30fcf840b44cb8b6291549b05768b23954616b4772fc45"},
                                                                 {"indicatorName": "MODIFY_OWN_PROCESS",
                                                                  "applicationName": "svc.exe",
                                                                  "sha256Hash": "a37dd4f85117539ce4401c02c2bea403d7a724bedaccb5969980c8cf39b2a01a"},
                                                                 {"indicatorName": "HAS_PACKED_CODE",
                                                                  "applicationName": "iexplore.exe",
                                                                  "sha256Hash": "422d380855c449e81a30fcf840b44cb8b6291549b05768b23954616b4772fc45"},
                                                                 {"indicatorName": "CODE_DROP",
                                                                  "applicationName": "iexplore.exe",
                                                                  "sha256Hash": "422d380855c449e81a30fcf840b44cb8b6291549b05768b23954616b4772fc45"},
                                                                 {"indicatorName": "RUN_MALWARE_APP",
                                                                  "applicationName": "iexplore.exe",
                                                                  "sha256Hash": "422d380855c449e81a30fcf840b44cb8b6291549b05768b23954616b4772fc45"},
                                                                 {"indicatorName": "RUN_ANOTHER_APP",
                                                                  "applicationName": "iexplore.exe",
                                                                  "sha256Hash": "422d380855c449e81a30fcf840b44cb8b6291549b05768b23954616b4772fc45"},
                                                                 {"indicatorName": "PACKED_CALL",
                                                                  "applicationName": "svc.exe",
                                                                  "sha256Hash": "a37dd4f85117539ce4401c02c2bea403d7a724bedaccb5969980c8cf39b2a01a"},
                                                                 {"indicatorName": "MALWARE_APP",
                                                                  "applicationName": "svc.exe",
                                                                  "sha256Hash": "a37dd4f85117539ce4401c02c2bea403d7a724bedaccb5969980c8cf39b2a01a"},
                                                                 {"indicatorName": "MODIFY_MEMORY_PROTECTION",
                                                                  "applicationName": "svc.exe",
                                                                  "sha256Hash": "a37dd4f85117539ce4401c02c2bea403d7a724bedaccb5969980c8cf39b2a01a"},
                                                                 {"indicatorName": "NEW_SCRIPT_DLL",
                                                                  "applicationName": "iexplore.exe",
                                                                  "sha256Hash": "422d380855c449e81a30fcf840b44cb8b6291549b05768b23954616b4772fc45"},
                                                                 {"indicatorName": "TARGET_MALWARE_APP",
                                                                  "applicationName": "iexplore.exe",
                                                                  "sha256Hash": "422d380855c449e81a30fcf840b44cb8b6291549b05768b23954616b4772fc45"},
                                                                 {"indicatorName": "KNOWN_ROGUE",
                                                                  "applicationName": "svc.exe",
                                                                  "sha256Hash": "a37dd4f85117539ce4401c02c2bea403d7a724bedaccb5969980c8cf39b2a01a"},
                                                                 {"indicatorName": "HAS_PACKED_CODE",
                                                                  "applicationName": "svc.exe",
                                                                  "sha256Hash": "a37dd4f85117539ce4401c02c2bea403d7a724bedaccb5969980c8cf39b2a01a"},
                                                                 {"indicatorName": "MALWARE_DROP",
                                                                  "applicationName": "iexplore.exe",
                                                                  "sha256Hash": "422d380855c449e81a30fcf840b44cb8b6291549b05768b23954616b4772fc45"}],
                                                  "time": 1460752321085},
                                   "url": "https://testserver.company.net/ui#investigate/events/device/2004122/incident/DRE26",
                                   "eventTime": 1460752321085, "eventId": "fadb33aa035211e6be8701df2c083974",
                                   "eventDescription": "[syslog alert] [Cb Defense has detected a threat against your company.] [https://testserver.company.net/ui#device/2004122/incident/DRE26] [An application has created an executable which is a known virus or on the Company Black List.] [Incident id: DRE26] [Threat score: 4] [Group: default] [Email: fakeav_driveby@company.net.demo] [Name: fakeav_driveby] [Type and OS: WINDOWS Windows 7 x86 SP: 0]\n",
                                   "deviceInfo": {"email": "COMPANY\\fakeav_driveby@company.net.demo",
                                                  "groupName": "default", "internalIpAddress": null,
                                                  "externalIpAddress": null, "deviceType": "WINDOWS",
                                                  "deviceVersion": "Windows 7 x86 SP: 0",
                                                  "targetPriorityType": "MEDIUM", "deviceId": 2004122,
                                                  "deviceName": "COMPANY\\fakeav_driveby",
                                                  "deviceHostName": null, "targetPriorityCode": 0},
                                   "ruleName": "syslog alert", "type": "THREAT"}, {
                                   "threatInfo": {"incidentId": "8OI0O", "score": 8,
                                                  "summary": "A known virus (Appetite: Keylogger, Password or Data stealer, Backdoor, Rootkit, Ransomware or Worm) attempted a network connection.",
                                                  "indicators": [{"indicatorName": "ATTEMPTED_CLIENT",
                                                                  "applicationName": "caretoosxdropper",
                                                                  "sha256Hash": "0710be16ba8a36712c3cac21776c8846e29897300271f09ba0a41983e370e1a0"},
                                                                 {"indicatorName": "BEACON",
                                                                  "applicationName": "caretoosxdropper",
                                                                  "sha256Hash": "0710be16ba8a36712c3cac21776c8846e29897300271f09ba0a41983e370e1a0"},
                                                                 {"indicatorName": "MALWARE_DROP",
                                                                  "applicationName": "xpcproxy",
                                                                  "sha256Hash": "ab0d18bd9d4a32e3b5cdc7e2231760833c0e6c2a315b479109df5bceae28b221"},
                                                                 {"indicatorName": "KNOWN_MALWARE_ON_NETWORK",
                                                                  "applicationName": "caretoosxdropper",
                                                                  "sha256Hash": "0710be16ba8a36712c3cac21776c8846e29897300271f09ba0a41983e370e1a0"},
                                                                 {"indicatorName": "MALWARE_APP",
                                                                  "applicationName": "caretoosxdropper",
                                                                  "sha256Hash": "0710be16ba8a36712c3cac21776c8846e29897300271f09ba0a41983e370e1a0"},
                                                                 {"indicatorName": "TARGET_MALWARE_APP",
                                                                  "applicationName": "xpcproxy",
                                                                  "sha256Hash": "ab0d18bd9d4a32e3b5cdc7e2231760833c0e6c2a315b479109df5bceae28b221"},
                                                                 {"indicatorName": "CODE_DROP",
                                                                  "applicationName": "xpcproxy",
                                                                  "sha256Hash": "ab0d18bd9d4a32e3b5cdc7e2231760833c0e6c2a315b479109df5bceae28b221"},
                                                                 {"indicatorName": "KNOWN_BACKDOOR",
                                                                  "applicationName": "caretoosxdropper",
                                                                  "sha256Hash": "0710be16ba8a36712c3cac21776c8846e29897300271f09ba0a41983e370e1a0"},
                                                                 {"indicatorName": "RUN_MALWARE_APP",
                                                                  "applicationName": "bash",
                                                                  "sha256Hash": "737867f9e519c2eae2b064c33dc0608b283ebd6045fcf8b19736651ec34c0e37"}],
                                                  "time": 1460752389112},
                                   "url": "https://testserver.company.net/ui#investigate/events/device/2004117/incident/8OI0O",
                                   "eventTime": 1460752389112, "eventId": "fadd7d9b035211e6be8701df2c083974",
                                   "eventDescription": "[syslog alert] [Cb Defense has detected a threat against your company.] [https://testserver.company.net/ui#device/2004117/incident/8OI0O] [A known virus (Appetite: Keylogger, Password or Data stealer, Backdoor, Rootkit, Ransomware or Worm) attempted a network connection.] [Incident id: 8OI0O] [Threat score: 8] [Group: default] [Email: caretoOsx@company.net.demo] [Name: Demo_CaretoMac] [Type and OS: MAC MAC OS X 10.9.0]\n",
                                   "deviceInfo": {"email": "COMPANY\\caretoOsx@company.net.demo",
                                                  "groupName": "default", "internalIpAddress": null,
                                                  "externalIpAddress": null, "deviceType": "MAC",
                                                  "deviceVersion": "MAC OS X 10.9.0",
                                                  "targetPriorityType": "MEDIUM", "deviceId": 2004117,
                                                  "deviceName": "COMPANY\\Demo_CaretoMac",
                                                  "deviceHostName": null, "targetPriorityCode": 0},
                                   "ruleName": "syslog alert", "type": "THREAT"}, {
                                   "threatInfo": {"incidentId": "3WTHN", "score": 8,
                                                  "summary": "A known virus (Appetite: Keylogger, Password or Data stealer, Backdoor, Rootkit, Ransomware or Worm) attempted a network connection.",
                                                  "indicators": [{"indicatorName": "BEACON",
                                                                  "applicationName": "caretoosxdropper",
                                                                  "sha256Hash": "0710be16ba8a36712c3cac21776c8846e29897300271f09ba0a41983e370e1a0"},
                                                                 {"indicatorName": "KNOWN_MALWARE_ON_NETWORK",
                                                                  "applicationName": "caretoosxdropper",
                                                                  "sha256Hash": "0710be16ba8a36712c3cac21776c8846e29897300271f09ba0a41983e370e1a0"},
                                                                 {"indicatorName": "MALWARE_APP",
                                                                  "applicationName": "caretoosxdropper",
                                                                  "sha256Hash": "0710be16ba8a36712c3cac21776c8846e29897300271f09ba0a41983e370e1a0"},
                                                                 {"indicatorName": "KNOWN_BACKDOOR",
                                                                  "applicationName": "caretoosxdropper",
                                                                  "sha256Hash": "0710be16ba8a36712c3cac21776c8846e29897300271f09ba0a41983e370e1a0"},
                                                                 {"indicatorName": "ATTEMPTED_CLIENT",
                                                                  "applicationName": "caretoosxdropper",
                                                                  "sha256Hash": "0710be16ba8a36712c3cac21776c8846e29897300271f09ba0a41983e370e1a0"}],
                                                  "time": 1460752389112},
                                   "url": "https://testserver.company.net/ui#investigate/events/device/2004117/incident/3WTHN",
                                   "eventTime": 1460752389112, "eventId": "faf9dfdd035211e6aab2b97cae4f83f3",
                                   "eventDescription": "[syslog alert] [Cb Defense has detected a threat against your company.] [https://testserver.company.net/ui#device/2004117/incident/3WTHN] [A known virus (Appetite: Keylogger, Password or Data stealer, Backdoor, Rootkit, Ransomware or Worm) attempted a network connection.] [Incident id: 3WTHN] [Threat score: 8] [Group: default] [Email: caretoOsx@company.net.demo] [Name: Demo_CaretoMac] [Type and OS: MAC MAC OS X 10.9.0]\n",
                                   "deviceInfo": {"email": "COMPANY\\caretoOsx@company.net.demo",
                                                  "groupName": "default", "internalIpAddress": null,
                                                  "externalIpAddress": null, "deviceType": "MAC",
                                                  "deviceVersion": "MAC OS X 10.9.0",
                                                  "targetPriorityType": "MEDIUM", "deviceId": 2004117,
                                                  "deviceName": "COMPANY\\Demo_CaretoMac",
                                                  "deviceHostName": null, "targetPriorityCode": 0},
                                   "ruleName": "syslog alert", "type": "THREAT"}, {
                                   "threatInfo": {"incidentId": "81RTK", "score": 2,
                                                  "summary": "Multiple commands were executed via a script.",
                                                  "indicators": [{"indicatorName": "RUN_ANOTHER_APP",
                                                                  "applicationName": "Payload.class",
                                                                  "sha256Hash": "6750c319c5d1ba2d2937ef602c2e5c03df6fb60449566e5efb0331310a655c4e"},
                                                                 {"indicatorName": "SCRIPT_COMMAND",
                                                                  "applicationName": "Payload.class",
                                                                  "sha256Hash": "6750c319c5d1ba2d2937ef602c2e5c03df6fb60449566e5efb0331310a655c4e"},
                                                                 {"indicatorName": "SCRIPT_COMMAND",
                                                                  "applicationName": "Payload.class",
                                                                  "sha256Hash": "f84adcc7dc36e494dc89fd1c81c30233c91d0cb875c6cf5171dea19ab55cb72f"},
                                                                 {"indicatorName": "RUN_ANOTHER_APP",
                                                                  "applicationName": "Payload.class",
                                                                  "sha256Hash": "9afae0b82960d6fce7544efba1cb0509522dc29ba76539b63c30b5afce86388f"},
                                                                 {"indicatorName": "RUN_ANOTHER_APP",
                                                                  "applicationName": "Payload.class",
                                                                  "sha256Hash": "f84adcc7dc36e494dc89fd1c81c30233c91d0cb875c6cf5171dea19ab55cb72f"}],
                                                  "time": 1460752391454},
                                   "url": "https://testserver.company.net/ui#investigate/events/device/2004119/incident/81RTK",
                                   "eventTime": 1460752391454, "eventId": "f6357957035211e6be8701df2c083974",
                                   "eventDescription": "[syslog alert] [Cb Defense has detected a threat against your company.] [https://testserver.company.net/ui#device/2004119/incident/81RTK] [Multiple commands were executed via a script.] [Incident id: 81RTK] [Threat score: 2] [Group: default] [Email: macReverseShell@company.net.demo] [Name: Demo_Mac_Shell] [Type and OS: MAC MAC OS X 10.9.0]\n",
                                   "deviceInfo": {"email": "COMPANY\\macReverseShell@company.net.demo",
                                                  "groupName": "default", "internalIpAddress": null,
                                                  "externalIpAddress": null, "deviceType": "MAC",
                                                  "deviceVersion": "MAC OS X 10.9.0",
                                                  "targetPriorityType": "MEDIUM", "deviceId": 2004119,
                                                  "deviceName": "COMPANY\\Demo_Mac_Shell",
                                                  "deviceHostName": null, "targetPriorityCode": 0},
                                   "ruleName": "syslog alert", "type": "THREAT"}], "success": true,
             "message": "Success"}
